### PR TITLE
update select2 css to use digest asset paths

### PR DESCRIPTION
**Pull request by ericcf**
* things worked in development, but on staging/production the path
  /assets/select2.png doesn't work because the png has a digest file
  name instead

[#94591980]

### CODE REVIEW

**Comment by michaelwehrley** [comment]
did you test this in development by changing `config.serve_static_assets = true` in development.rb?

**Comment by michaelwehrley** [comment]
And I believe then you can run `rake assets:precompile`

**Comment by ericcf** [comment]
I tested directly on staging, because unless you're using precompiled assets locally it's not the same test.

**Comment by michaelwehrley** [comment]
Right, that is why I was suggesting to make the change in the development.rb file.  Regardless, :eyeglasses: as good as :pizza:

**Comment by ericcf** [comment]
`serve_static_assets` isn't the correct change in that case. You'd need `config.assets.digest = true`.

**Comment by michaelwehrley** [comment]
:+1:

**Pull request merged**
